"use client";
import { useState } from "react";
import { dataBr, moeda, hojeBrasil } from "@/lib/cobrancas";
import type { NotaFinanceira } from "@/lib/visao-financeira";
import { filtrarNotasFiscais, resumoFiscal, baseSimplesPorNotas } from "@/lib/resumo-fiscal";
import { ApuracoesPgdas } from "./apuracoes-pgdas";
const painel="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6";
const nomes={iss:"ISS declarado",pis:"PIS retido",cofins:"COFINS retido",inss:"INSS retido",ir:"IR retido",csll:"CSLL retido"};
export function FaturamentoFiscal({notas,inicio,fim,busca,empresa}:{notas:NotaFinanceira[];inicio:string;fim:string;busca:string;empresa:"sysney"|"drsoft"}){
  const [situacao,setSituacao]=useState("");
  const [selecionadas,setSelecionadas]=useState<string[]>([]);
  const [mesSimples,setMesSimples]=useState(hojeBrasil().slice(0,7));
  const base=baseSimplesPorNotas(notas,mesSimples);
  const lista=filtrarNotasFiscais(notas,inicio,fim,busca,situacao);
  const selecao=lista.filter(n=>selecionadas.includes(n.numero));
  const resumo=resumoFiscal(selecao.length?selecao:lista);
  const marcar=(numero:string)=>setSelecionadas(v=>v.includes(numero)?v.filter(n=>n!==numero):[...v,numero]);
  const link=(numero:string,tipo:string)=>`/api/admin/nfse?empresa=${empresa}&historico=1&numero=${encodeURIComponent(numero)}&arquivo=${tipo}`;
  return <div className="space-y-5">
    <ApuracoesPgdas empresa={empresa} notas={notas} inicio={inicio} fim={fim}/>
    <section className="rounded-2xl bg-[#071b30] p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-cyan-300">Fonte fiscal · XML das notas</p><h3 className="mt-2 text-xl font-bold">O que foi faturado, sem confundir com recebimentos</h3><p className="mt-3 text-sm leading-6 text-slate-300">Esta aba usa sempre a data fiscal de emissão, as datas inicial/final e a busca por cliente ou nota. O filtro bancário de situação não se aplica aqui. Os totais representam o histórico consultado, não uma apuração contábil.</p></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Faturamento válido",moeda(resumo.faturado),`${resumo.validas} notas válidas`],["Notas canceladas",moeda(resumo.valorCancelado),`${resumo.canceladas} notas · excluídas do faturamento`],["Situação a conferir",String(resumo.desconhecidas),"Excluídas do faturamento válido"],["Imposto efetivamente pago","Não apurado","Depende de guias e comprovantes; não é zero"]].map(([titulo,valor,descricao])=><section key={titulo} className={painel}><p className="text-xs font-semibold text-slate-500">{titulo}</p><p className="mt-3 text-xl font-bold text-slate-900">{valor}</p><p className="mt-2 text-xs leading-5 text-slate-500">{descricao}</p></section>)}</div>
<section className={painel}><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Conferência do Simples Nacional</p><h3 className="mt-2 text-lg font-bold text-slate-900">Base de referência para conferir a contabilidade</h3></div><label className="text-xs font-semibold text-slate-500">Mês de referência<input type="month" className="mt-2 block rounded-xl border border-slate-200 p-3 text-sm" value={mesSimples} onChange={e=>setMesSimples(e.target.value)}/></label></div>{base&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-blue-50 p-4"><p className="text-xs text-blue-800">Notas válidas emitidas no mês selecionado</p><p className="mt-2 text-2xl font-bold text-blue-900">{moeda(base.receitaMes)}</p></div><div className="rounded-xl bg-blue-50 p-4"><p className="text-xs text-blue-800">Notas válidas nos 12 meses anteriores · referência, não RBT12 confirmado</p><p className="mt-2 text-2xl font-bold text-blue-900">{moeda(base.receita12)}</p><p className="mt-2 text-xs text-blue-800">{dataBr(base.inicio)} a {dataBr(base.fim)} · {base.mesesComNotas} meses com notas válidas</p></div></div>}<p className="mt-4 text-xs leading-5 text-slate-500">Usa todas as notas importadas desta empresa, sem filtro por cliente ou seleção individual. Datas são de emissão: receitas de outra fonte, cancelamentos posteriores, início de atividade e diferenças de competência exigem conferência. Mês sem nota não é automaticamente mês sem receita.</p><div className="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-4"><h4 className="text-sm font-bold text-blue-900">Apuração oficial e referência por notas são fontes diferentes</h4><p className="mt-2 text-xs leading-5 text-blue-900">As declarações PGDAS-D importadas aparecem no painel acima. Esta base por notas serve para conferência, não substitui a receita declarada nem valida o enquadramento das atividades. Para períodos ainda não declarados, a estimativa continua dependendo de revisão das regras e atividades; não repetimos automaticamente o último percentual. ISS zero na nota não significa DAS zero.</p></div></section>
    <section className={painel}><h3 className="text-lg font-bold text-slate-900">Tributos informados nas notas válidas</h3><p className="mt-2 text-xs leading-5 text-slate-500">São valores declarados nos XML, não pagamentos realizados. Campo ausente é “não informado”, nunca zero presumido. Não somamos ISS e retenções como se fossem uma única obrigação. O DAS do Simples não é calculado pela soma desses campos.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{resumo.tributos.map(t=><div key={t.campo} className="rounded-xl bg-blue-50 p-4"><p className="text-xs font-semibold text-blue-800">{nomes[t.campo]}</p><p className="mt-2 text-xl font-bold text-blue-900">{t.informadas?moeda(t.valor):"Não informado"}</p><p className="mt-2 text-xs text-blue-800">{t.informadas} de {resumo.validas} notas com campo informado{t.campo==="iss"?` · ISS retido informado: ${moeda(resumo.issRetido)}`:""}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-slate-500">{resumo.guiasComData} notas com data de quitação de guia informada pela Prefeitura. Essa data pode se repetir em várias notas da mesma guia; não comprova o valor total pago, nem a quitação de DAS/DARF. Consulte guias e comprovantes.</p></section>
    <section className={painel}><div className="flex flex-wrap items-center justify-between gap-4"><div><h3 className="text-lg font-bold text-slate-900">Selecione as notas para conferir</h3><p className="mt-2 text-xs text-slate-500">{selecao.length?`Totais das ${selecao.length} notas selecionadas neste filtro`:`Totais das ${lista.length} notas neste filtro`} · A seleção não altera documentos.</p></div><label className="text-xs font-semibold text-slate-500">Situação fiscal<select className="ml-2 rounded-xl border border-slate-200 bg-white p-2.5 text-sm" value={situacao} onChange={e=>{setSituacao(e.target.value);setSelecionadas([]);}}><option value="">Todas</option><option value="N">Válidas</option><option value="C">Canceladas</option></select></label></div><div className="mt-4 flex gap-4 text-sm"><button className="font-semibold text-blue-700" onClick={()=>setSelecionadas(lista.map(n=>n.numero))}>Selecionar deste filtro</button><button className="font-semibold text-slate-500" onClick={()=>setSelecionadas([])}>Limpar seleção</button></div>
    <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Selecionar","Nota / cliente","Emissão","Valor fiscal","Situação","ISS / retido","Guia / quitação","Documentos"].map(t=><th key={t} className="p-3">{t}</th>)}</tr></thead><tbody>{lista.map(n=><tr key={n.numero} className="border-b border-slate-100 align-top"><td className="p-3"><input type="checkbox" aria-label={`Selecionar nota ${n.numero}`} checked={selecionadas.includes(n.numero)} onChange={()=>marcar(n.numero)}/></td><td className="max-w-[250px] p-3"><p className="font-semibold text-slate-900">NFS-e {n.numero}</p><p className="mt-1 text-xs text-slate-500">{n.cliente}</p></td><td className="p-3 whitespace-nowrap">{dataBr(n.emissao.slice(0,10))}</td><td className="p-3 whitespace-nowrap font-semibold">{moeda(n.centavos)}</td><td className="p-3">{n.situacao==="N"?"Válida":n.situacao==="C"?"Cancelada":"A conferir"}{n.tributos?.cancelamento&&<p className="mt-1 text-xs text-slate-500">Em {dataBr(n.tributos.cancelamento)}</p>}</td><td className="p-3">{n.tributos?.iss!=null?moeda(n.tributos.iss):"Não informado"}<p className="mt-1 text-xs text-slate-500">{n.tributos?.issRetido===true?"Retido":n.tributos?.issRetido===false?"Não retido":"Retenção não informada"}</p></td><td className="p-3 text-xs text-slate-500">{n.tributos?.guia||"Guia não informada"}<p className="mt-1">{n.tributos?.quitacaoGuia?dataBr(n.tributos.quitacaoGuia):"Quitação não informada"}</p></td><td className="p-3 whitespace-nowrap">{n.xml&&<a href={link(n.numero,"xml")} className="mr-3 font-semibold text-blue-700">XML</a>}{n.pdf&&<a href={link(n.numero,"pdf")} className="font-semibold text-blue-700">PDF</a>}</td></tr>)}</tbody></table></div>{!lista.length&&<p className="p-5 text-sm text-slate-500">Nenhuma nota importada neste filtro. Isso não comprova ausência de faturamento.</p>}</section>
  </div>;
}
