"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { dataBr, moeda, type Empresa } from "@/lib/cobrancas";
import { resumoRegularizacao, type RegularizacaoFiscal } from "@/lib/regularizacao-fiscal";
import { lerRespostaAdmin } from "@/lib/admin-resposta";
import { MensagemAdmin, useConfirmarAdmin } from "./dialogos-admin";
const input="mt-1 w-full rounded-xl border border-slate-300 bg-white p-3 text-sm";
const botao="rounded-xl border border-blue-200 bg-white px-4 py-2 text-sm font-bold text-blue-800 disabled:opacity-50";
export function RegularizacaoFiscalPainel({empresa}:{empresa:Empresa}) {
  const [registros,setRegistros]=useState<RegularizacaoFiscal[]>([]),[editando,setEditando]=useState<RegularizacaoFiscal|null>(null);
  const [inicio,setInicio]=useState(""),[fim,setFim]=useState(""),[aviso,setAviso]=useState(""),[erro,setErro]=useState(false),[ocupado,setOcupado]=useState(false);
  const [carregado,setCarregado]=useState(false);
  const confirmar=useConfirmarAdmin();
  const carregar=useCallback(async(signal?:AbortSignal)=>{
    setOcupado(true);
    try {const r=await fetch(`/api/admin/cobrancas?empresa=${empresa}&regularizacao=1`,{cache:"no-store",signal}); const d=await lerRespostaAdmin<{registros:RegularizacaoFiscal[];erro?:string}>(r);if(!r.ok)throw Error(d.erro);if(!Array.isArray(d.registros))throw Error("O serviço financeiro ainda não disponibiliza o controle de regularização. É necessário atualizar a API junto com o painel.");setRegistros(d.registros);setCarregado(true);}
    catch(e){if(!signal?.aborted){setErro(true);setAviso(e instanceof Error?e.message:"Consulta indisponível.");}}
    finally{if(!signal?.aborted)setOcupado(false);}
  },[empresa]);
  useEffect(()=>{const abort=new AbortController();const id=requestAnimationFrame(()=>void carregar(abort.signal));return()=>{cancelAnimationFrame(id);abort.abort();};},[carregar]);
  const lista=registros.filter(r=>(!inicio||r.recebimento>=inicio)&&(!fim||r.recebimento<=fim)), resumo=resumoRegularizacao(lista);
  async function salvar(e:FormEvent<HTMLFormElement>){
    e.preventDefault();if(!editando||ocupado)return;const f=new FormData(e.currentTarget);
    const body={acao:"planejar-regularizacao",id:editando.id,atualizadoEm:editando.atualizadoEm,competencia:f.get("competencia"),evidenciaCompetencia:f.get("evidencia"),emissaoPlanejada:f.get("planejada"),nota:f.get("nota")};
    if(!await confirmar({titulo:"Salvar planejamento fiscal?",subtitulo:"Recebimento já pago por PIX",descricao:"Esta ação apenas registra a revisão. Não emite nota, não cria boleto e não envia cobrança. A data planejada não altera a competência do serviço nem a apuração tributária.",confirmar:"Salvar controle",detalhes:[{rotulo:"Cliente",valor:editando.cliente},{rotulo:"Valor recebido",valor:moeda(editando.centavos)},{rotulo:"Competência",valor:String(body.competencia||"A confirmar")},{rotulo:"Nota existente",valor:String(body.nota||"Sem vínculo confirmado")}]}))return;
    setOcupado(true);
    try{const r=await fetch(`/api/admin/cobrancas?empresa=${empresa}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await lerRespostaAdmin<{erro?:string}>(r,true);if(!r.ok)throw Error(d.erro);setEditando(null);setErro(false);setAviso("Planejamento salvo. Nenhum documento foi emitido e nenhum e-mail foi enviado.");await carregar();}
    catch(e){setErro(true);setAviso(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setOcupado(false);}
  }
  return <section className="space-y-5">
    <header className="rounded-3xl bg-[#071b30] p-7 text-white"><p className="text-xs font-bold uppercase tracking-widest text-cyan-300">{empresa.toUpperCase()} · Regularização fiscal</p><h2 className="mt-2 text-2xl font-black">Valores recebidos, notas a conferir</h2><p className="mt-3 max-w-3xl text-sm text-slate-300">Organize o histórico já pago e planeje a regularização em etapas, preservando as datas reais. Estes valores não são dívidas do cliente.</p></header>
    <p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">Não use o mês do PIX como competência automaticamente. Confira o período na memória de cálculo ou contrato e as notas existentes antes de emitir. Planejamento não muda a competência tributária e não agenda emissão automática.</p>
    <div className="flex flex-wrap items-end gap-4"><label className="text-sm font-semibold">Recebimentos desde<input type="date" className={input} value={inicio} onChange={e=>setInicio(e.target.value)}/></label><label className="text-sm font-semibold">Até<input type="date" className={input} value={fim} min={inicio||undefined} onChange={e=>setFim(e.target.value)}/></label><button className={botao} disabled={ocupado} onClick={()=>void carregar()}>Atualizar consulta</button><button className={botao} onClick={()=>{setInicio("");setFim("");}}>Todo o histórico</button></div>
    <div className="grid gap-4 md:grid-cols-3">{[{titulo:"Recebido por PIX",valor:moeda(resumo.recebido),detalhe:`${resumo.recebimentos} recebimento(s)`},{titulo:"Sem nota vinculada",valor:moeda(resumo.semNotaVinculada),detalhe:"Não é saldo a cobrar nem imposto calculado"},{titulo:"Notas vinculadas",valor:moeda(resumo.vinculado),detalhe:`${resumo.conferir} registro(s) ainda exigem conferência`}].map(c=><article key={c.titulo} className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-sm text-slate-600">{c.titulo}</h3><p className="mt-2 text-2xl font-black text-slate-950">{carregado?c.valor:"…"}</p><p className="mt-2 text-xs text-slate-500">{carregado?c.detalhe:"Aguardando a consulta"}</p></article>)}</div>
    {ocupado&&<p aria-live="polite" className="text-sm text-slate-600">Consultando o controle…</p>}
    <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{["Cliente / contato","Pagamento","Valor","Competência do serviço","Referência de vencimento","Situação fiscal","Planejamento","Ação"].map(h=><th key={h} className="whitespace-nowrap p-4">{h}</th>)}</tr></thead><tbody>{lista.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="min-w-60 p-4"><strong>{r.cliente}</strong><p className="text-xs text-slate-500">{r.documento}<br/>{r.contato} · {r.email}</p></td><td className="whitespace-nowrap p-4"><span className="font-semibold text-emerald-700">Pago · PIX</span><p>{dataBr(r.recebimento)}</p><p className="text-xs text-slate-500">Inclusão no banco: {r.inclusaoBanco}</p></td><td className="whitespace-nowrap p-4">{moeda(r.centavos)}</td><td className="p-4">{r.competencia?r.competencia.split("-").reverse().join("/"):"A confirmar"}</td><td className="p-4">{dataBr(r.vencimentoReferencia)}<p className="text-xs text-slate-500">Dia 12 · referência, não nova cobrança</p></td><td className="p-4">{r.nota?`NFS-e ${r.nota} vinculada`:r.notasCandidatas.length?"Conferir nota existente":"Sem nota vinculada"}</td><td className="p-4">{r.nota?"Já documentado":r.emissaoPlanejada?dataBr(r.emissaoPlanejada):"A definir"}</td><td className="p-4"><button className={botao} disabled={ocupado} onClick={()=>setEditando(r)}>Revisar e planejar</button></td></tr>)}</tbody></table></div>
    {carregado&&!ocupado&&!lista.length&&<p className="text-sm text-slate-500">Nenhum recebimento importado neste período e empresa. Ausência de registro não comprova ausência de pagamento.</p>}
    {editando&&<form key={editando.id} onSubmit={e=>void salvar(e)} className="space-y-4 rounded-2xl border border-blue-200 bg-white p-6"><h3 className="text-lg font-bold">Revisar {editando.cliente} · PIX de {dataBr(editando.recebimento)}</h3><p className="text-sm text-slate-600">{editando.descricao} · {moeda(editando.centavos)}</p>{editando.notasCandidatas.map(n=><p className="rounded-xl bg-blue-50 p-3 text-sm" key={n.numero}>Nota candidata {n.numero} · {dataBr(n.emissao.slice(0,10))} · {moeda(n.centavos)} · {n.descricao}. Confira antes de vincular.</p>)}<div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold">Competência real<input type="month" name="competencia" className={input} defaultValue={editando.competencia}/></label><label className="text-sm font-semibold">Nota existente (opcional)<input name="nota" inputMode="numeric" className={input} defaultValue={editando.nota}/></label><label className="text-sm font-semibold">Data planejada de regularização<input type="date" name="planejada" className={input} defaultValue={editando.emissaoPlanejada}/></label></div><label className="block text-sm font-semibold">Origem da competência / observações de conferência<textarea name="evidencia" className={input} maxLength={1000} defaultValue={editando.evidenciaCompetencia} placeholder="Ex.: memória de cálculo enviada pelo Álvaro, referente a junho/2026"/></label><div className="flex gap-3"><button className={botao} disabled={ocupado}>Salvar planejamento — sem emitir</button><button type="button" className={botao} onClick={()=>setEditando(null)}>Fechar revisão</button></div></form>}
    <MensagemAdmin mensagem={aviso} aoFechar={()=>setAviso("")} titulo={erro?"Não foi possível concluir":"Planejamento registrado"} subtitulo="Controle de regularização fiscal" tom={erro?"erro":"info"}/>
  </section>;
}
