"use client";
import { useState } from "react";
import { dataBr, moeda } from "@/lib/cobrancas";
import type { FiltroFinanceiro, LinhaFinanceira, NotaFinanceira } from "@/lib/visao-financeira";
import { analisarClientes, auditarEmissoes, compararFinanceiro, compararNotas, serieMensalNotas, diasEntre, ordenarClientes, variacaoPercentual, type OrdemClientes } from "@/lib/analise-financeira";

const painel = "rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6";
export function RelatoriosFinanceiros({ linhas, filtradas, filtro, hoje, notas }: { linhas: LinhaFinanceira[]; filtradas: LinhaFinanceira[]; filtro: FiltroFinanceiro; hoje: string; notas: NotaFinanceira[] }) {
  const [ordem, setOrdem] = useState<OrdemClientes>("pontualidade");
  const [todos, setTodos] = useState(false);
  const comparacao = compararFinanceiro(linhas, filtro, hoje);
  const fiscal = compararNotas(notas, filtro.inicio || "", filtro.fim || "", filtro.busca);
  const mensal = serieMensalNotas(notas, filtro.inicio || "", filtro.fim || "", filtro.busca);
  const clientes = ordenarClientes(analisarClientes(filtradas), ordem);
  const auditoria = auditarEmissoes(filtradas, hoje);
  const percentual = (atual: number, anterior: number) => {
    const v = variacaoPercentual(atual, anterior);
    return v === null ? "Sem base anterior" : `${v >= 0 ? "+" : ""}${v.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%`;
  };
  return <div className="space-y-5">
    {mensal.length > 0 && <section className={painel}><h3 className="text-lg font-bold text-slate-900">Notas mês a mês</h3><p className="mt-2 text-xs leading-5 text-slate-500">Cada mês é comparado com seu equivalente no ano anterior, dentro das datas selecionadas. Mês sem nota importada pede conferência; não comprova esquecimento ou obrigação de emitir.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[660px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Mês", "Notas emitidas", "Valor fiscal", "Notas no ano anterior", "Valor no ano anterior"].map(v=><th className="p-3 font-semibold" key={v}>{v}</th>)}</tr></thead><tbody>{mensal.map(m=><tr key={m.mes} className="border-b border-slate-100"><td className="p-3 font-semibold text-slate-900">{m.mes.split("-").reverse().join("/")}<p className="mt-1 text-xs font-normal text-slate-500">{dataBr(m.inicio)} a {dataBr(m.fim)}</p></td><td className="p-3">{m.atual.quantidade || <span className="text-xs text-amber-800">Sem nota importada</span>}</td><td className="p-3 font-semibold text-blue-800">{moeda(m.atual.valor)}</td><td className="p-3">{m.anterior.quantidade}</td><td className="p-3 text-slate-600">{moeda(m.anterior.valor)}</td></tr>)}</tbody></table></div>{mensal.length===240 && <p className="mt-3 text-xs text-amber-800">A análise mensal exibe no máximo 240 meses. Reduza o intervalo para conferir os períodos restantes.</p>}</section>}

    <section className={painel}>
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Comparativo anual</p><h3 className="mt-2 text-lg font-bold text-slate-900">Mesmo período, ano anterior</h3></div><span className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-800">Mesmos filtros de cliente e situação</span></div>
      {comparacao ? <>
        <p className="mt-3 text-sm text-slate-600">{dataBr(filtro.inicio!)} a {dataBr(filtro.fim!)} × {dataBr(comparacao.periodo.inicio)} a {dataBr(comparacao.periodo.fim)}</p>
        <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[580px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Indicador", "Período selecionado", "Ano anterior", "Variação"].map(v => <th key={v} className="p-3 font-semibold">{v}</th>)}</tr></thead><tbody>{[
          ["Cobranças emitidas (valor nominal)", comparacao.atual.emitidos, comparacao.anterior.emitidos, true],
          ["Recebimentos das cobranças selecionadas", comparacao.atual.recebido, comparacao.anterior.recebido, true],
          ["Cobranças com pagamento registrado", comparacao.atual.pagos, comparacao.anterior.pagos, false],
        ].map(([nome, atual, anterior, dinheiro]) => <tr key={String(nome)} className="border-b border-slate-100"><td className="p-3 text-slate-600">{nome}</td><td className="p-3 font-semibold text-blue-800">{dinheiro ? moeda(Number(atual)) : String(atual)}</td><td className="p-3 font-semibold text-slate-700">{dinheiro ? moeda(Number(anterior)) : String(anterior)}</td><td className="p-3 text-xs text-slate-500">{percentual(Number(atual), Number(anterior))}</td></tr>)}</tbody></table></div>
        <p className="mt-4 text-xs leading-5 text-slate-500">{comparacao.atual.registros} registros no período atual; {comparacao.anterior.registros} no anterior. Histórico disponível não garante cobertura completa. Ausência de registros não prova ausência de faturamento. Situações são as últimas registradas, não uma reconstrução do saldo daquele ano. Para comparar entradas por data de baixa, selecione “Baixa / pagamento registrado”.</p>
        {filtro.fim! > hoje && <p className="mt-2 text-xs text-amber-800">O período inclui datas futuras. Não compare o ano atual incompleto como se já estivesse encerrado; use “Ano até hoje” para a comparação equivalente.</p>}
      </> : <p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Selecione data inicial e final. “Este mês” compara o mês equivalente; “Ano até hoje” compara o mesmo intervalo do ano anterior; “Ano completo” inclui o ano inteiro.</p>}
      {fiscal && <div className="mt-5 rounded-xl border border-blue-100 bg-blue-50 p-4"><h4 className="text-sm font-bold text-blue-900">Comparação fiscal: notas emitidas na Prefeitura</h4><p className="mt-2 text-xs leading-5 text-blue-900">Fonte independente dos boletos, sempre pela data fiscal de emissão e busca por cliente. Não somar ao valor das cobranças. Notas canceladas ou com situação desconhecida não entram no valor.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><p className="text-xs text-blue-800">Período selecionado · {fiscal.atual.quantidade} notas</p><p className="mt-2 text-xl font-bold text-blue-900">{moeda(fiscal.atual.valor)}</p><p className="mt-1 text-xs text-blue-800">{fiscal.atual.canceladas} canceladas · {fiscal.atual.desconhecidas} a conferir</p></div><div><p className="text-xs text-blue-800">Mesmo período do ano anterior · {fiscal.anterior.quantidade} notas</p><p className="mt-2 text-xl font-bold text-blue-900">{moeda(fiscal.anterior.valor)}</p><p className="mt-1 text-xs text-blue-800">Variação: {percentual(fiscal.atual.valor, fiscal.anterior.valor)}</p></div></div></div>}
    </section>

    <section className={painel}>
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Perfil de recebimento</p><h3 className="mt-2 text-lg font-bold text-slate-900">Regularidade e pontualidade por cliente</h3></div>
        <label className="text-xs font-semibold text-slate-500">Ordenar por<select className="mt-2 block rounded-xl border border-slate-200 bg-white p-2.5 text-sm text-slate-800" value={ordem} onChange={e => setOrdem(e.target.value as OrdemClientes)}><option value="pontualidade">Maior pontualidade registrada</option><option value="atraso">Maior atraso registrado</option><option value="regularidade">Mais meses com recebimento</option><option value="valor">Maior valor recebido</option></select></label>
      </div>
      <p className="mt-3 rounded-xl bg-blue-50 p-4 text-xs leading-5 text-blue-900">No Inter, a data disponível é a baixa bancária, não necessariamente quando o cliente pagou. Dias são corridos e podem incluir compensação e fins de semana. “Mais meses com recebimento” mede recorrência no histórico, não é uma avaliação de crédito nem prova de fidelidade contratual.</p>
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Cliente", "Liquidadas / com data", "Até o vencimento", "Após vencimento", "Atraso médio / máximo", "Meses com recebimento", "Valor recebido"].map(v => <th key={v} className="p-3 font-semibold">{v}</th>)}</tr></thead><tbody>{(todos ? clientes : clientes.slice(0, 8)).map(c => <tr key={c.id} className="border-b border-slate-100 align-top"><td className="max-w-[260px] p-3"><p className="font-semibold text-slate-900">{c.nome}</p><p className="mt-1 text-xs text-slate-500">{c.baixasBancarias ? `${c.baixasBancarias} baixas bancárias` : "Registros manuais"}{c.semData ? ` · ${c.semData} sem data` : ""}</p></td><td className="p-3">{c.liquidadas} / {c.comData}</td><td className="p-3"><strong className="text-emerald-700">{c.comData ? `${Math.round(c.noPrazo / c.comData * 100)}%` : "—"}</strong><p className="mt-1 text-xs text-slate-500">{c.noPrazo} registro(s)</p></td><td className="p-3">{c.aposVencimento}</td><td className="p-3">{c.comData ? `${c.atrasoMedio.toLocaleString("pt-BR", { maximumFractionDigits: 1 })} / ${c.atrasoMaximo} dias` : "Sem data para avaliar"}</td><td className="p-3">{c.mesesRecebidos}</td><td className="whitespace-nowrap p-3 font-semibold text-blue-800">{moeda(c.recebido)}</td></tr>)}</tbody></table></div>
      {!clientes.length && <p className="mt-4 text-sm text-slate-500">Nenhuma cobrança emitida com dados para este filtro.</p>}
      {clientes.length > 8 && <button className="mt-4 text-sm font-semibold text-blue-700 hover:underline" onClick={() => setTodos(v => !v)}>{todos ? "Mostrar principais clientes" : `Ver os ${clientes.length} clientes`}</button>}
    </section>

    <section className={painel}><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Auditoria de emissão</p><h3 className="mt-2 text-lg font-bold text-slate-900">Competências que merecem conferência</h3>
      <div className="mt-5 grid gap-3 sm:grid-cols-3">{[["Prazo chegou, sem nota vinculada", auditoria.pendentes.length], ["Nota emitida depois do dia previsto", auditoria.tardias.length], ["Nota sem data fiscal importada", auditoria.semDataFiscal.length]].map(([nome, total]) => <div key={nome} className="rounded-xl bg-slate-50 p-4"><p className="text-2xl font-bold text-slate-900">{total}</p><p className="mt-2 text-xs text-slate-600">{nome}</p></div>)}</div>
      <p className="mt-4 text-xs leading-5 text-slate-500">A análise usa apenas a recorrência cadastrada e datas fiscais confirmadas. Sem nota vinculada é uma pendência a conferir, não prova de que você esqueceu de emitir. Antes do início dos planos cadastrados, faltam contratos e competências esperadas para detectar lacunas com segurança.</p>
      {[...auditoria.pendentes.map(r => ({ r, motivo: "Sem nota vinculada; conferir portal / histórico" })), ...auditoria.tardias.map(r => ({ r, motivo: `Emitida em ${dataBr(r.emissaoNota)} · ${diasEntre(r.emissaoPrevista, r.emissaoNota)} dia(s) após o dia previsto` }))].map(({ r, motivo }) => <div key={r.id} className="mt-3 flex flex-wrap justify-between gap-3 rounded-xl border border-amber-100 bg-amber-50 p-4"><div><p className="text-sm font-semibold text-slate-900">{r.cliente}</p><p className="mt-1 text-xs text-slate-600">Competência {r.competencia.split("-").reverse().join("/")} · Dia previsto {dataBr(r.emissaoPrevista)}</p></div><p className="text-xs text-amber-900">{motivo}</p></div>)}
    </section>
  </div>;
}
