import Image from "next/image";
import Link from "next/link";

export type CommercialPageData = {
  eyebrow: string; title: string; lead: string;
  image: { src: string; alt: string; width: number; height: number };
  benefits: { title: string; text: string }[];
  processTitle: string; process: { title: string; text: string }[];
  audienceTitle: string; audiences: string[];
  faq: { question: string; answer: string }[];
};

const links = [["Força de vendas", "/sistema-forca-de-vendas"], ["Vendas B2B", "/plataforma-vendas-b2b"], ["Franquias e multimarcas", "/vendas-para-franquias-e-multimarcas"], ["Integrações ERP", "/integracoes-erp"]] as const;

export function CommercialPage({ data }: { data: CommercialPageData }) {
  return <main className="min-h-screen bg-white text-slate-950">
    <section className="relative overflow-hidden bg-[#07111f] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,#2563eb66,transparent_32%),radial-gradient(circle_at_bottom_left,#0891b244,transparent_30%)]" /><div className="relative mx-auto max-w-7xl px-6 py-7 lg:px-8">
      <header className="flex flex-wrap items-center justify-between gap-5"><Link href="/" className="flex items-center gap-3" aria-label="Página inicial do SISBlink"><Image src="/logo.png" alt="SYSNEY Informática" width={150} height={150} priority className="h-auto w-28 md:w-32" /><span className="hidden border-l border-white/20 pl-4 text-xl font-black text-blue-400 sm:block">SISBLINK</span></Link><nav aria-label="Soluções" className="hidden gap-5 text-sm font-semibold text-slate-200 xl:flex">{links.map(([label, href]) => <Link key={href} href={href} className="transition hover:text-sky-300">{label}</Link>)}</nav><Link href="/contato" className="rounded-full bg-blue-500 px-5 py-3 text-sm font-black shadow-lg shadow-blue-500/30 transition hover:bg-blue-400">Solicitar demonstração</Link></header>
      <div className="grid items-center gap-12 py-16 lg:grid-cols-[0.92fr_1.08fr] lg:py-24"><div><p className="text-sm font-black uppercase tracking-[0.3em] text-sky-300">{data.eyebrow}</p><h1 className="mt-5 text-4xl font-black leading-[1.04] tracking-tight sm:text-5xl lg:text-6xl">{data.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">{data.lead}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/contato" className="rounded-full bg-blue-500 px-7 py-4 text-center font-black transition hover:bg-blue-400">Ver o SISBlink em ação</Link><Link href="/" className="rounded-full border border-white/30 px-7 py-4 text-center font-black transition hover:bg-white/10">Conhecer a plataforma</Link></div></div><div className="rounded-2xl border border-white/10 bg-white/5 p-3 shadow-2xl shadow-black/30"><Image src={data.image.src} alt={data.image.alt} width={data.image.width} height={data.image.height} sizes="(min-width: 1024px) 52vw, 100vw" priority className="h-auto w-full rounded-lg bg-white object-contain" /></div></div>
    </div></section>
    <section className="px-6 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 md:grid-cols-2 lg:grid-cols-3">{data.benefits.map(item => <article key={item.title} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><span className="block h-1 w-12 rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" /><h2 className="mt-6 text-xl font-black text-blue-800">{item.title}</h2><p className="mt-3 leading-7 text-slate-700">{item.text}</p></article>)}</div></section>
    <section className="bg-[#eef5fb] px-6 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2"><div><p className="text-sm font-black uppercase tracking-[0.3em] text-blue-700">Operação conectada</p><h2 className="mt-4 text-3xl font-black tracking-tight md:text-4xl">{data.processTitle}</h2><div className="mt-8 space-y-5">{data.process.map((item, index) => <div key={item.title} className="flex gap-4 rounded-2xl bg-white p-5 shadow-sm"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-600 font-black text-white">{index + 1}</span><div><h3 className="font-black">{item.title}</h3><p className="mt-1 leading-7 text-slate-600">{item.text}</p></div></div>)}</div></div><div><p className="text-sm font-black uppercase tracking-[0.3em] text-blue-700">Para quem é</p><h2 className="mt-4 text-3xl font-black tracking-tight md:text-4xl">{data.audienceTitle}</h2><ul className="mt-8 grid gap-4 sm:grid-cols-2">{data.audiences.map(item => <li key={item} className="rounded-2xl border border-blue-100 bg-white p-5 font-bold text-slate-800 shadow-sm">✓ {item}</li>)}</ul></div></div></section>
    <section className="px-6 py-20 lg:px-8"><div className="mx-auto max-w-4xl"><p className="text-center text-sm font-black uppercase tracking-[0.3em] text-blue-700">Dúvidas frequentes</p><h2 className="mt-4 text-center text-3xl font-black tracking-tight md:text-4xl">Entenda como o SISBlink se adapta à operação</h2><div className="mt-10 space-y-4">{data.faq.map(item => <details key={item.question} className="rounded-2xl border border-slate-200 p-5"><summary className="cursor-pointer list-none pr-6 font-black">{item.question}</summary><p className="mt-3 leading-7 text-slate-600">{item.answer}</p></details>)}</div></div></section>
    <section className="bg-blue-600 px-6 py-20 text-center text-white"><h2 className="text-3xl font-black md:text-5xl">Sua operação B2B pode vender com mais clareza e controle.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-blue-100">Converse com a SYSNEY e avalie o SISBlink no contexto real da sua empresa, equipe comercial e ERP.</p><Link href="/contato" className="mt-8 inline-flex rounded-full bg-white px-8 py-4 font-black text-blue-700 transition hover:bg-slate-100">Solicitar demonstração</Link></section>
    <footer className="bg-[#07111f] px-6 py-10 text-slate-400"><div className="mx-auto flex max-w-7xl flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="font-black text-white">SYSNEY Informática</p><p className="text-sm">SISBlink — força de vendas B2B para moda.</p></div><div className="flex flex-wrap gap-4 text-sm">{links.map(([label, href]) => <Link key={href} href={href} className="hover:text-white">{label}</Link>)}</div></div></footer>
  </main>;
}
