import type { Metadata } from "next";
import { CommercialPage, type CommercialPageData } from "../components/commercial-page";
export const metadata: Metadata = { title: "Vendas para Franquias e Lojas Multimarcas", description: "Sistema B2B para vender coleções a franquias e lojas multimarcas, com catálogo digital, pedidos por cliente, grades, preços e gestão comercial.", alternates: { canonical: "/vendas-para-franquias-e-multimarcas" } };
const data: CommercialPageData = {
  eyebrow: "Vendas para franquias e multimarcas", title: "Atenda redes, franquias e lojistas com uma jornada comercial organizada.", lead: "Cada cliente B2B possui contexto próprio. O SISBlink ajuda a indústria e sua força de vendas a apresentar coleções, trabalhar pedidos e revisar condições com clareza, sem perder as particularidades de cada loja ou grupo.",
  image: { src: "/sisblink/pedidos.webp", alt: "Gestão de pedidos para franquias e multimarcas no SISBlink", width: 1363, height: 767 },
  benefits: [{ title: "Carteira organizada", text: "Localize clientes por grupo e critérios comerciais, preservando o escopo permitido para cada usuário." }, { title: "Pedido por loja ou cliente", text: "Mantenha cada pedido associado ao cliente correto, com sua tabela, histórico e informações comerciais." }, { title: "Coleção visual", text: "Apresente produtos com imagens, cores, grades e prazos em uma navegação pensada para o atendimento." }, { title: "Redes e grupos de acesso", text: "A estrutura multiempresa e os grupos comerciais apoiam operações com marcas, empresas e conjuntos de clientes." }, { title: "Acompanhamento de campanha", text: "Indicadores ajudam gestores a entender cobertura de carteira, vendas e oportunidades durante a coleção." }, { title: "Revisão com o comprador", text: "A confirmação oferece uma leitura consolidada do pedido antes da finalização e do envio." }],
  processTitle: "Mais consistência em cada atendimento B2B", process: [{ title: "Acesse a carteira autorizada", text: "O usuário encontra clientes e pedidos dentro de seu perfil e grupo comercial." }, { title: "Monte o mix por cliente", text: "O catálogo apoia a escolha de produtos, variações e quantidades no contexto daquela loja." }, { title: "Confira o pedido", text: "A etapa final reúne o que foi comprado e as condições necessárias para a confirmação." }],
  audienceTitle: "Para operações que vendem a uma rede diversa", audiences: ["Franqueadoras", "Lojas franqueadas", "Redes de lojas próprias", "Lojas multimarcas", "Grupos de compradores", "Representantes regionais"],
  faq: [{ question: "É possível separar pedidos por cliente ou loja?", answer: "Sim. O pedido é carregado e validado no contexto do cliente e do usuário autorizado." }, { question: "A plataforma atende franquias e multimarcas ao mesmo tempo?", answer: "O SISBlink foi desenhado para diferentes canais B2B. A configuração de empresas, marcas, usuários e integrações define como cada operação será atendida." }, { question: "O gestor acompanha o desempenho da carteira?", answer: "A plataforma possui painéis e indicadores comerciais. A disponibilidade de cada métrica depende dos dados e das regras configuradas para a empresa." }],
};
export default function Page() { return <CommercialPage data={data} />; }
