import type { Metadata } from "next";
import { CommercialPage, type CommercialPageData } from "../components/commercial-page";
export const metadata: Metadata = { title: "Plataforma de Vendas B2B para Moda e Atacado", description: "Plataforma de vendas B2B para moda e atacado com showroom digital, catálogo, pedidos, clientes e confirmação comercial.", alternates: { canonical: "/plataforma-vendas-b2b" } };
const data: CommercialPageData = {
  eyebrow: "Plataforma de vendas B2B", title: "Transforme a coleção em uma experiência digital preparada para vender.", lead: "O SISBlink aproxima indústria, representantes e clientes em uma jornada visual. Da apresentação dos produtos à revisão do pedido, cada etapa mantém o contexto comercial necessário para uma venda B2B mais clara.",
  image: { src: "/sisblink/catalogo-pedido.webp", alt: "Catálogo digital para vendas B2B do SISBlink", width: 1916, height: 1073 },
  benefits: [{ title: "Showroom digital", text: "Organize a coleção por linha, grupo, referência e outros filtros comerciais, com imagens e variações do produto." }, { title: "Pedido no contexto do cliente", text: "Preço, tabela e regras são tratados conforme o cliente e o pedido autorizado, sem cálculos sensíveis no frontend." }, { title: "Grades e disponibilidade", text: "Consulte tamanhos, cores, prazos e estoque conforme a configuração e a realidade integrada da operação." }, { title: "Busca e navegação comercial", text: "Encontre produtos, itens já comprados, favoritos e oportunidades sem perder o pedido em andamento." }, { title: "Revisão antes do envio", text: "Confira produtos, quantidades, valores e condições comerciais em uma etapa própria de confirmação." }, { title: "Acesso por perfil", text: "Representantes, gestores, clientes e operadores recebem experiências coerentes com seu papel." }],
  processTitle: "Do showroom ao pedido confirmado", process: [{ title: "Prepare a coleção", text: "Produtos, imagens, grades, preços e disponibilidade chegam ao ambiente comercial pelas integrações definidas." }, { title: "Conduza o atendimento", text: "Navegue pelo catálogo e registre quantidades no pedido certo, inclusive em uma operação com múltiplos clientes." }, { title: "Finalize com segurança", text: "Revise informações e use os canais de confirmação configurados, com rastreabilidade operacional." }],
  audienceTitle: "Venda B2B para diferentes modelos comerciais", audiences: ["Atacado de moda", "Indústrias de confecção", "Calçados e acessórios", "Redes e grupos de lojas", "Showrooms e representantes", "Operações com coleções"],
  faq: [{ question: "O SISBlink é um e-commerce B2C?", answer: "Não. Seu foco é a operação comercial B2B, com clientes, representantes, tabelas, pedidos e regras próprias do atacado." }, { question: "É possível trabalhar com vários pedidos?", answer: "Sim. A operação moderna foi desenhada para manter pedidos selecionados e o pedido em foco, respeitando o contexto de cada cliente." }, { question: "O catálogo mostra informações reais da operação?", answer: "Os dados disponíveis são fornecidos pela API e pelas integrações configuradas, com revalidação de acesso, preço e disponibilidade no backend." }],
};
export default function Page() { return <CommercialPage data={data} />; }
