import type { Metadata } from "next";
import { CommercialPage, type CommercialPageData } from "../components/commercial-page";
export const metadata: Metadata = { title: "Integração ERP para Força de Vendas B2B", description: "Integre catálogo, clientes, preços, estoque e pedidos B2B ao ERP com APIs, webservices, arquivos e rotinas adequadas à sua operação.", alternates: { canonical: "/integracoes-erp" } };
const data: CommercialPageData = {
  eyebrow: "Integrações ERP e ecossistema comercial", title: "Conecte a força de vendas aos dados que sustentam sua operação.", lead: "O SISBlink pode integrar produtos, clientes, tabelas, estoque e pedidos ao ecossistema da empresa. O desenho considera o ERP, as regras comerciais e a qualidade dos dados existentes, em vez de impor uma integração genérica.",
  image: { src: "/sisblink/dashboard.webp", alt: "Dados comerciais integrados no dashboard SISBlink", width: 1263, height: 847 },
  benefits: [{ title: "Produtos e coleções", text: "Receba cadastros, imagens, categorias e atributos necessários para apresentar o mix comercial." }, { title: "Clientes e tabelas", text: "Mantenha o contexto de clientes, grupos e preços coerente com as regras da empresa." }, { title: "Estoque e disponibilidade", text: "Sincronize os dados usados na consulta comercial conforme a fonte e a frequência acordadas." }, { title: "Pedidos para o ERP", text: "Estruture o retorno dos pedidos e status para reduzir redigitação e rupturas no processo." }, { title: "APIs e webservices", text: "Use interfaces modernas ou adapte rotinas existentes conforme as possibilidades do sistema de origem." }, { title: "Implantação orientada", text: "Mapeamento, validação e homologação fazem parte da definição de uma integração confiável." }],
  processTitle: "Integração começa pelo entendimento dos dados", process: [{ title: "Mapeamento", text: "Identificamos sistemas, cadastros, regras, responsáveis e frequência necessária para cada informação." }, { title: "Conexão e validação", text: "Implementamos o fluxo adequado — API, webservice, arquivo ou rotina dedicada — com validações de segurança." }, { title: "Homologação e operação", text: "Os cenários reais são conferidos antes da entrada em produção e acompanhados durante a evolução." }],
  audienceTitle: "Integrações avaliadas conforme cada cenário", audiences: ["Linx e Microvix", "EasyLinx", "Bling", "Outros ERPs de mercado", "APIs e webservices", "Arquivos e rotinas legadas"],
  faq: [{ question: "O SISBlink integra com qualquer ERP?", answer: "A viabilidade depende das interfaces, dados e regras disponíveis no ERP. A SYSNEY avalia cada cenário antes de confirmar o escopo." }, { question: "É necessário trocar o ERP atual?", answer: "Não necessariamente. A proposta é conectar a camada comercial ao ecossistema existente quando houver meios técnicos seguros para isso." }, { question: "A integração acontece em tempo real?", answer: "Pode ser em tempo real ou por sincronizações programadas. A frequência adequada depende do dado, do ERP e dos requisitos da operação." }],
};
export default function Page() { return <CommercialPage data={data} />; }
