import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { SisblinkTour } from "../components/sisblink-tour";

const title = "SISBlink em ação: catálogo, pedidos por grade e atendimento ao vivo";
const description = "Veja telas reais do SISBlink: dashboard, catálogo digital de moda atacado, shopping B2B, pedidos por cor e tamanho, confirmação, chat e espelhamento do pedido.";
const socialImage = { url: "/sisblink/telas/catalogo.webp", width: 1920, height: 1080, alt: "Catálogo digital e pedido por grade no SISBlink" };
export const metadata: Metadata = {
  title, description, alternates: { canonical: "/sisblink-em-acao" },
  openGraph: { title, description, url: "/sisblink-em-acao", type: "website", locale: "pt_BR", siteName: "SISBlink", images: [socialImage] },
  twitter: { card: "summary_large_image", title, description, images: [socialImage.url] },
};

const differentiators = [
  ["Especialização na venda de moda", "Coleção, cor, tamanho, grade e prazo fazem parte da conversa comercial. O SISBlink reúne esses detalhes no contexto do produto e do pedido."],
  ["Venda assistida com experiência visual", "O representante apresenta a coleção, o lojista acompanha o catálogo espelhado e os dois conversam na sessão. Atendimento e escolha dos produtos caminham juntos."],
  ["Qualidade que você pode conferir", "Avalie as telas, monte uma grade e percorra a revisão na demonstração. A experiência de uso pode ser comparada com o fluxo que sua equipe precisa executar."],
  ["Entrega definida para sua operação", "Na avaliação comercial, alinhe catálogo, regras, integração, implantação e suporte. Escopo e etapas claros ajudam sua equipe a saber o que será entregue."],
];

export default function Page() {
  return <main className="min-h-screen bg-white text-slate-950">
    <section className="relative overflow-hidden bg-[#07111f] px-6 text-white lg:px-10">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,#155e7566,transparent_60%)]" />
      <div className="relative mx-auto max-w-[1600px]">
        <header className="flex flex-wrap items-center justify-between gap-4 py-7"><Link href="/" aria-label="SYSNEY — página inicial"><Image src="/logo.png" alt="SYSNEY Informática" width={150} height={150} className="h-auto w-28" /></Link><nav aria-label="Navegação da demonstração" className="flex flex-wrap items-center gap-5 text-sm font-bold"><Link href="/sistema-pedidos-confeccao-moda" className="text-slate-300 hover:text-sky-300">Pedidos para moda</Link><Link href="/contato" className="rounded-full bg-blue-500 px-5 py-3 hover:bg-blue-400">Solicitar demonstração</Link></nav></header>
        <div className="pb-12 pt-12 sm:pt-16"><p className="text-sm font-black uppercase tracking-[0.25em] text-emerald-300">SISBlink em ação · Tecnologia SYSNEY</p><h1 className="mt-5 max-w-5xl text-4xl font-black leading-[1.08] tracking-tight sm:text-5xl lg:text-6xl">Uma coleção bem apresentada.<br /><span className="text-sky-300">Um pedido bem conduzido.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">Do catálogo digital de moda ao pedido por grade, o SISBlink combina apresentação visual, controle comercial e atendimento ao vivo. Veja o funcionamento e descubra o que faz diferença na rotina de marcas, representantes e lojistas.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#telas" className="rounded-full bg-emerald-400 px-7 py-4 font-black text-slate-950 hover:bg-emerald-300">Explorar as telas ↓</Link><Link href="/contato?origem=sisblink-em-acao&interesse=avaliacao" className="rounded-full border border-white/30 px-7 py-4 font-black hover:bg-white/10">Avaliar minha operação</Link></div></div>
        <figure className="rounded-t-2xl border border-b-0 border-white/15 bg-white/5 p-2 shadow-2xl sm:p-4"><Image src="/sisblink/telas/catalogo.webp" alt="Tela real do SISBlink com coleção de moda, catálogo visual e montagem por tamanho e prazo" width={1920} height={1080} preload sizes="(min-width: 1600px) 1560px, 100vw" className="h-auto w-full rounded-lg object-contain" /><figcaption className="px-2 py-3 text-xs leading-6 text-slate-400">Captura em 1920 × 1080 do ambiente de demonstração DRSOFT. SISBlink é a plataforma desenvolvida pela SYSNEY.</figcaption></figure>
      </div>
    </section>
    <SisblinkTour />
    <section className="bg-[#07111f] px-6 py-16 text-white sm:py-24 lg:px-10"><div className="mx-auto max-w-[1600px]"><p className="text-sm font-black uppercase tracking-[0.2em] text-emerald-300">O diferencial está no atendimento</p><h2 className="mt-4 max-w-4xl text-3xl font-black leading-tight sm:text-4xl">Mais proximidade para negociar. Mais clareza para comprar.</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Com o espelhamento do pedido, o cliente acompanha o catálogo apresentado e mantém a conversa no chat da sessão. O representante conduz o atendimento sem perder o contexto comercial.</p><figure className="mt-9 rounded-2xl border border-white/15 bg-white/5 p-3"><Image src="/sisblink/telas/espelhamento.webp" alt="Cliente acompanhando o catálogo sincronizado no espelhamento do pedido SISBlink" width={1920} height={1080} sizes="(min-width: 1600px) 1560px, 100vw" className="h-auto w-full rounded-lg object-contain" /><figcaption className="px-2 pt-3 text-xs leading-6 text-slate-400">Visualização do cliente em uma sessão de demonstração. O link de acesso dessa sessão foi encerrado após as capturas.</figcaption></figure><div className="mt-8 grid gap-5 md:grid-cols-3">{[["Catálogo sincronizado", "O cliente acompanha os produtos apresentados pelo representante."], ["Sugestão de grade", "O lojista pode propor quantidades por tamanho para validação do representante."], ["Conversa no pedido", "Chat e atendimento compartilham a referência do pedido em negociação."]].map(([heading, text]) => <article key={heading} className="rounded-2xl border border-white/15 bg-white/5 p-6"><h3 className="text-lg font-black text-sky-200">{heading}</h3><p className="mt-3 leading-7 text-slate-300">{text}</p></article>)}</div></div></section>
    <section className="px-6 py-16 sm:py-24 lg:px-10"><div className="mx-auto max-w-[1600px]"><p className="text-sm font-black uppercase tracking-[0.2em] text-blue-700">Experiência, funcionamento e entrega</p><h2 className="mt-4 max-w-4xl text-3xl font-black tracking-tight sm:text-4xl">Tecnologia feita para os detalhes da sua venda.</h2><div className="mt-10 grid gap-6 md:grid-cols-2">{differentiators.map(([heading, text]) => <article key={heading} className="rounded-3xl border border-slate-200 bg-slate-50 p-7"><span className="block h-1 w-12 rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" /><h3 className="mt-5 text-xl font-black text-blue-800">{heading}</h3><p className="mt-3 leading-8 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="bg-[#eef5fb] px-6 py-16 sm:py-24 lg:px-10"><div className="mx-auto max-w-6xl"><p className="text-sm font-black uppercase tracking-[0.2em] text-blue-700">Qualidade e custo-benefício</p><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">Compare o que você recebe. Avalie o investimento com o mesmo critério.</h2><p className="mt-6 max-w-4xl text-lg leading-8 text-slate-600">A SYSNEY propõe uma plataforma especializada e uma avaliação próxima da sua operação. Traga o fluxo que sua equipe usa e compare funcionalidade, integração, implantação e suporte no mesmo escopo. A proposta comercial define o investimento para o seu cenário.</p><ol className="mt-8 grid gap-5 md:grid-cols-3">{[["1. Demonstre sua rotina", "Coleção, tabela, grade, entrega e canais de venda."], ["2. Valide o funcionamento", "Catálogo, atendimento, pedido e regras comerciais."], ["3. Compare a proposta", "Escopo, etapas de implantação, suporte e custo total."]].map(([heading, text]) => <li key={heading} className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="font-black text-blue-800">{heading}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></li>)}</ol><div className="mt-8 flex flex-wrap gap-x-7 gap-y-3 font-bold text-blue-700"><Link href="/sistema-pedidos-confeccao-moda">Pedidos para confecção e moda →</Link><Link href="/integracoes-erp">Integração ao ERP →</Link><Link href="/compras-reposicao-multimarcas">Compras e reposição multimarcas →</Link></div></div></section>
    <section className="bg-blue-600 px-6 py-16 text-center text-white sm:py-24"><h2 className="text-3xl font-black sm:text-4xl">Veja o SISBlink com o olhar da sua equipe.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-blue-100">Solicite uma demonstração para avaliar os recursos, alinhar a entrega e receber uma proposta para sua operação.</p><Link href="/contato?origem=sisblink-em-acao&interesse=avaliacao" className="mt-8 inline-flex rounded-full bg-white px-8 py-4 font-black text-blue-700 hover:bg-slate-100">Solicitar demonstração e proposta</Link></section>
    <footer className="bg-[#07111f] px-6 py-8 text-center text-sm text-slate-400"><Link href="/" className="font-bold text-sky-300">SYSNEY Informática · SISBlink</Link><p className="mt-3">Recursos e condições comerciais são avaliados conforme o escopo e a configuração da operação.</p></footer>
  </main>;
}
